---
title: "Fuzzer Evaluation - $BENCHMARK"
output: html_document
params:
  benchmark: '$BENCHMARK'
  artifactURL: "https://ci.in.ripley.cloud/logs"
  dataDirs: '$DATADIRS'
  baseDir: "/ci-logs/"
---
Evaluation generated {{<param ReportDate >}}, using revision [{{<param Revision >}}]({{<param CodeURL >}}).

Configuration:
* Campaign duration: {{<param Duration >}}
* Number of trials: {{<param Trials >}}


```{r st1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(purrr)
library(tibble)
library(readr)
library(dplyr)
library(stringr)
library(ggplot2)
library(knitr)
library(rjson)
library(kableExtra)
```

```{r include=FALSE}
readResultFile <- function(file, config) {
  read_csv(file) %>%
          add_column(filename = file, config=config) %>%
          extract(filename, into = c("path","filename"), regex = "(.*)/([^/]*_plot_data.*)") %>%
          extract(filename, into = c("index"),".*_plot_data_(\\d+)",remove=FALSE)%>%
          mutate(
                  campaignSecs = `# unix_time` - min(`# unix_time`))
}


readExperimentResults <- function(dataDir) {
  list.files(path=dataDir$path, recursive = F,
             pattern=paste0(params$benchmark,"_plot_data_*"),
             full.names = TRUE) %>% map_df(~readResultFile(.,dataDir$name)) %>%
          group_by(campaignSecs, config, path, filename, index) %>%
          summarise(cov = first(paths_total),
                    invalid_inputs = first(invalid_inputs),
                    valid_inputs = first(valid_inputs))
}

# Load plot_data
configs <- fromJSON(params$dataDirs)$dataDirs
data <- map_dfr(configs, readExperimentResults)
byFile <- data %>%
        mutate(campaignMins = floor(campaignSecs / 60)) %>%
        complete(filename, campaignMins) %>%
        fill(cov) %>%
        group_by(filename, index)

summary <- byFile %>%
        group_by(campaignMins, config) %>%
        summarise(
                cov.avg = mean(cov),
                cov.min = min(cov),
                cov.max = max(cov),
                inputs.avg = mean(invalid_inputs + valid_inputs),
                inputs.min = min(invalid_inputs + valid_inputs),
                inputs.max = max(invalid_inputs + valid_inputs)
        )

# Load JaCoCo branch data
readJaCoCo <- function(dataDir){
  jsonFile <- paste0(dataDir$path,"/",params$benchmark,"_jacoco_summary.json")
  if(file.exists(jsonFile)){
    as.data.frame(fromJSON(file=jsonFile)) %>% add_column(config=dataDir$name)
  } else{
    data.frame(config=c(dataDir$name),branchesCovered=c(NA),branchesTotal=c(NA))
  }
}


jacoco <- map_dfr(configs, readJaCoCo)

```

## Branch Probes Over Time

```{r echo = FALSE}
ggplot(
        data = summary,
        aes(x = campaignMins, y = cov.avg, group = config, color = config)
) +
        geom_ribbon(aes(ymin = cov.min, ymax = cov.max, group = config, fill = config),
                    linetype = 0, alpha = 0.3) +
        geom_line(size = 0.35) +
        theme_linedraw() +
        xlab("Campaign Time (minutes)") +
        ylab("Branch Probes Covered") +
        theme(text = element_text(size = 6), axis.line = element_line(colour = "black", size = 0.01))
```

### Final branch coverage by fuzzing config
```{r echo = FALSE, message = FALSE, results='asis'}
summaryCoverageTable <- byFile %>%
        group_by(filename, path, config) %>%
        summarise(probesHit = max(cov)) %>%
        group_by(config, path) %>%
        summarise(Average.probesHit = mean(probesHit), SD.probesHit = sd(probesHit)) %>%
        ungroup()%>%
        left_join(jacoco,by="config") %>%
        mutate(
                path=substring(path,nchar(params$baseDir)),
                config=paste0("[",config,"](",params$artifactURL,"/",path,"/jacoco-",params$benchmark,")")) %>%
        rename(Configuration=config, Covered=branchesCovered,Total=branchesTotal)  %>%
        relocate(Covered,.before=Total) %>% select(-path)
names(summaryCoverageTable) <- gsub("[.].+", "", names(summaryCoverageTable))
kable(summaryCoverageTable, booktabs=TRUE, digits=0, format.args = list(big.mark = ",",
                                                                        scientific = FALSE)) %>%
        add_header_above(c("","JQF Probes"=2,"JaCoCo Branches"=2))
```

### Final branch coverage by fuzzing run
```{r echo = FALSE,  results='asis'}
branchCovByFuzzingRun <- byFile %>%
        group_by(filename) %>%
        summarise(`Probes Hit` = max(cov))

kable(branchCovByFuzzingRun, booktabs=TRUE, digits=0, format.args = list(big.mark = ",",
                                                                         scientific = FALSE))
```


## Inputs Over Time

```{r  echo = FALSE}

ggplot(
        data = summary,
        aes(x = campaignMins, y = inputs.avg, group = config, color = config)
) +
        geom_ribbon(aes(ymin = inputs.min, ymax = inputs.max, group = config, fill = config), linetype = 0, alpha = 0.3) +
        geom_line(size = 0.35) +
        theme_linedraw() +
        xlab("Campaign Time (minutes)") +
        ylab("Inputs Executed") +
        theme(text = element_text(size = 6), axis.line = element_line(colour = "black", size = 0.01))
```

### Final count of inputs executed by fuzzing config
```{r echo = FALSE, message = FALSE,  results='asis'}
inputsByFile <- byFile %>%
        group_by(filename, config) %>%
        summarise(invalid_inputs = max(invalid_inputs),
                  valid_inputs = max(valid_inputs),
                  total_inputs = max(invalid_inputs) + max(valid_inputs))

summaryInputsTable <- inputsByFile %>% group_by(config) %>% summarise(
        avg.invalid_inputs = mean(invalid_inputs), sd.invalid_inputs = sd(invalid_inputs),
        avg.valid_inputs = mean(valid_inputs), sd.valid_inputs = sd(valid_inputs),
        avg.total_inputs = mean(total_inputs), sd.total_inputs = sd(total_inputs))
names(summaryInputsTable) <- gsub("[.].+", "", names(summaryInputsTable))

kable(summaryInputsTable, booktabs=TRUE, digits=0, format.args = list(big.mark = ",",
                                                                      scientific = FALSE))  %>%
        add_header_above(c("","Invalid Inputs"=2,"Valid Inputs"=2,"Total Inputs"=2))
```

### Final count of inputs executed by fuzzing run
```{r echo = FALSE,  results='asis'}
kable(byFile %>% group_by(filename) %>% summarise(invalid_inputs = max(invalid_inputs), valid_inputs = max(valid_inputs), total_inputs = max(invalid_inputs) + max(valid_inputs)), booktabs=TRUE, digits=0, format.args = list(big.mark = ",",
                                                                                                                                                                                                                               scientific = FALSE))
```
