name: evaluate
on: [workflow_dispatch]
jobs:
  eval-24h:
    runs-on: self-hosted
    strategy:
      matrix:
        evalTarget: [ 'edu.berkeley.cs.jqf.examples.bcel.ParserTest', 'edu.berkeley.cs.jqf.examples.closure.CompilerTest', 'edu.berkeley.cs.jqf.examples.ant.ProjectBuilderTest',
        'edu.berkeley.cs.jqf.examples.maven.ModelReaderTest','edu.berkeley.cs.jqf.examples.rhino.CompilerTest']
        runNumber: [1,2,3,4,5]
    steps:
      - uses: actions/checkout@v2
      - name: Build JQF
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64/
        run: mvn -B -DskipTests install
      - name: Run Fuzzer
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64/
        run: cd examples && mvn -fn -Dquiet jqf:fuzz -Dclass=${{ matrix.evalTarget }} -Dmethod=testWithGenerator -Dtime=24h
      - name: Archive Plot Data
        uses: actions/upload-artifact@v2
        with:
          name: plot_data_${{ matrix.evalTarget }}_${{ matrix.runNumber }}
          path: examples/target/fuzz-results/**/plot_data
      - name: Archive all fuzz results
        uses: actions/upload-artifact@v2
        with:
          name: fuzz-results_${{ matrix.evalTarget }}_${{ matrix.runNumber }}
          path: |
            examples/target/fuzz-results
            !examples/target/fuzz-results/**/plot_data
