name: Gold evaluation - 24 hours, 20 trials
on: workflow_dispatch
jobs:
  evaluate:
    uses: jon-bell/jqf/.github/workflows/evaluation-workflow.yml@reporting-ci
    with:
      duration: 24h
      trials: 20
      JVM_OPTS: -Xmx12g
    secrets:
      INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
